name: swap slot to production environment
on: 
  workflow_dispatch:
    inputs:
      slot:
        description: 'App service slot name to swap with PRODUCTION (for example, `staging` or `v1.2.3`)'     
        required: true
        default: 'staging'

env:
  APP_NAME: ${{ github.event.repository.name }}
  RESOURCE_GROUP_NAME: ${{ secrets.BUILDING_BLOCKS_CENTRALUS_NONPROD_RESOURCE_GROUP }}

jobs:
  swap-slot:
    name: Swap slot into production environment
    runs-on: ubuntu-latest
    steps:
    - name: 🔄 Login via Azure CLI ☁️
      uses: azure/login@v1
      with:
        creds: ${{ secrets.BUILDING_BLOCKS_CENTRALUS_NONPROD_AZURE_CREDENTIALS }}
    - name: 🔄 Swap slot with production ☁️
      run: az webapp deployment slot swap --name ${{ env.APP_NAME }} --slot ${{ github.event.inputs.slot }} --resource-group ${{ env.RESOURCE_GROUP_NAME }}
