name: swap slot to test environment
on: 
  workflow_dispatch:
    inputs:
      slot:
        description: 'App service slot name in nonprod to swap with TEST'     
        required: true
        default: 'dev'

env:
  APP_NAME: ${{ github.event.repository.name }}
  RESOURCE_GROUP_NAME: ${{ secrets.BUILDING_BLOCKS_CENTRALUS_NONPROD_RESOURCE_GROUP }}

jobs:
  swap-slot:
    name: Swap slot into test environment
    runs-on: ubuntu-latest
    steps:
    - name: 🔄 Login via Azure CLI ☁️
      uses: azure/login@v1
      with:
        creds: ${{ secrets.BUILDING_BLOCKS_CENTRALUS_NONPROD_AZURE_CREDENTIALS }}
    - name: 🔄 Swap slot with test ☁️
      run: az webapp deployment slot swap --name ${{ env.APP_NAME }}-nonprod --slot ${{ github.event.inputs.slot }} --resource-group ${{ env.RESOURCE_GROUP_NAME }}
